src/react-jw-player.jsx

Check if script is already loaded before currying initialize into onLoad. This fixes https://github.com/micnews/react-jw-player/issues/5.

Check if script is already loaded before currying initialize into onLoad

---

README.md
package.json
src/default-props.js
src/helpers/get-player-opts.js
src/prop-types.js
test/get-player-opts.test.js

This PR lets users add a `file` property instead of the original `playlist` option. If both are given, `playlist` will be given the priority.  Fixes https://github.com/micnews/react-jw-player/issues/4
Minor Change!
* Allow `file` to be passed in as a prop.
* Adds linting to test script.
* Updates README to reflect new props.

Add ability to play individual files, not just playlists.

---

README.md
src/default-props.js
src/helpers/get-player-opts.js
src/prop-types.js
test/get-player-opts.test.js

This allows the user to pass `isAutoPlay` and have the video load with autoplay capabilities. If not present, it will not override the defaults set in the loaded player script.
Also fixes an issue where `aspectratio` property was being set to `undefined` rather than not being set on the opts object at all.

Autoplay Abilities

---

package.json

Remove redundant dependency. This also prevents users from installing unnecessary extraneous dependencies that might result in a broken environment. For example, a user might have configurations for eslint 2.2.0, this ends up replacing it with a more later version of eslint where their configurations are not compatible.

move miclint from dependencies to devDependencies

---

README.md
src/helpers/get-player-opts.js
src/prop-types.js
test/get-player-opts.test.js

So we don't have to keep adding explicit support to features of the JW Player API, I'm proposing adding in a `customProps` object. Anything inside will be directly applied to the props on the JW Player instance rendered. Example:
```
customProps={{ skin: { name: 'six' } }}
```
Would result in passing `skin: { name: 'six'}` to JW Player's set-up command. This should make things more lightweight in the future, and give us the option of eventually completely deprecating most of the API matching we did in the initial version of this library.

Add the ability to pass in custom props.

---

README.md
package.json
src/prop-types.js

Added prop-types and react-test-renderer.
Updated README.md with new prop-types library.
Please test. :)

Fix React.PropTypes, ReactTestUtils and Shallow renderer deprecation notices

---

src/prop-types.js
test/get-player-opts.test.js
test/react-jw-player.browser-test.js

Allow to pass an array to the `playlist` prop.
Fixes #30

Allow array for playlist PropTypes

---

.npmignore

Using your component with webpack result on this error:
```
ERROR in ./~/react-jw-player/dist/react-jw-player.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/home/travis/build/coorpacademy/node_modules/react-jw-player"
```
This PR removes dev stuffs from npm distribution.

improved npmignore

---

src/react-jw-player.jsx
test/react-jw-player.test.jsx

Taken from this PR, but adding test coverage: https://github.com/micnews/react-jw-player/pull/16
There have been several complaints about server/client matching due to the nature of how JW Player handles the div that you inject it into. This PR solves that problem.

Render JW Player into an Un-Tracked Div in React

---

README.md
src/default-props.js
src/helpers/initialize.js
src/prop-types.js
test/initialize.test.js

This PR adds an `onAdSkipped` prop that takes a function that should run whenever the skip button is pressed on an ad.

Add `onAdSkipped` event

---

src/helpers/remove-jw-player-instance.js
src/react-jw-player.jsx
test/remove-jw-player-instance.test.js

Taken from https://github.com/micnews/react-jw-player/pull/28 but added test coverage!
This PR removes the player on unmount, which prevents a bug in some implementations in which audio from one video can keep running after the video has left the page.

Remove Player on Unmount

---

src/default-props.js
src/helpers/get-player-opts.js
src/prop-types.js
test/get-player-opts.test.js

Many times you want to inherit the mute and autostart properties from your player, as they are both configured on it.
Previously to this PR, this component defaulted both to `false`, which was overriding the configuration set on the player.
It is still possible to override player setup by passing a concrete value of `true` or `false` in the `ReactJWPlayer` component's `isMuted` and `isAutoPlay` props.

Added inheritance of player config for isMuted and isAutoPlay

---

src/react-jw-player.jsx
test/react-jw-player.browser-test.js

There is a bug where if you quickly change props before jwplayer initializes, the component crashes at the attempt to re-initialize. This prevents that.

Do not re-initialize an un-initialized component

---

src/create-event-handlers/on-time.js
src/default-props.js
test/on-time.test.js

Type: Minor 
I know https://github.com/micnews/react-jw-player/issues/54 is in the works, but for some things I'm working on right now having the onTime event handler that maps to the jwplayer own on('time') event just makes things so much easier, and I realized that adding it like this wasn't a big task. 
But @danmakenoise let me know if you think this makes sense or not!

Adding .onTime event that maps to jwPlayers own on('time') event.

---

src/default-props.js
src/helpers/initialize.js
src/prop-types.js
test/initialize.test.js

Type: Minor
Add callbacks for `buffer` and `bufferChange` events. Nothing special going on with those, just callbacking whenever they are triggered from the player, so didn't add any tests for it as I felt that was unnecessary. But let me know if you disagree and/or have any ideas for how to test this properly!

Add buffer callbacks

---

README.md
src/default-props.js
src/helpers/initialize.js
src/prop-types.js
test/initialize.test.js

I have notices that the adComplete hook was missing. This PR adds it, as well as tests for it and a Read.me entry

Added missing adComplete event hook

---

README.md
src/helpers/initialize.js
test/initialize.test.js

This PR resolves https://github.com/micnews/react-jw-player/issues/85, as well as implements the changes we requested in https://github.com/micnews/react-jw-player/pull/64 and https://github.com/micnews/react-jw-player/pull/66.
It turns out we were never passing an `onError` event handler on down. So, I switched it to a prop. Now users can do `onError={myErrorHandler}` and capture both setup errors, and normal errors.
I see no reason to distinguish between those error types until someone finds that absolutely necessary. (I don't believe at Mic we were ever interested in distinguishing those events)

Allow onError to be passed through as a prop to error events

---

README.md
src/helpers/get-event-name-from-prop.js
src/helpers/initialize.js
test/get-event-name-from-prop.test.js

Currently, we have to explicitly add event props to the library if we want the component to correctly assign props to JW Player events. This means that whenever JW Player changes props, we need to change our code, too. A better solution is to dynamically take all props named `onFoobar` and setup them up with JW Player through `player.on('foobar', props.onFoobar)`. 
This code accomplishes that while maintaining the event hooks _we_ created, like `onUnmute`, as well as maintaining functionality we had patched, like that for `onPlay`.
This should prevent us from needing to modify the code anytime a user requests a new event handler be added!
We naively take all props that begin with `on` and apply them as events to JW Player. This puts the onus on users to match the API, but should be worth …

Allow Dynamic Event Props

---

src/create-event-handlers/on-before-play.js
test/on-before-play.test.js

Having an issue where preroll is being played twice. While debugging I noticed that onPlay was not being called on the first preroll, so .hasPlayed is still set to false in onBeforePlay. Also checking if the ad has played before playing ad fixes the issue!

Fix preroll running twice

---

package.json
src/react-jw-player.jsx

we are regenerating a playlist via redux that ends up being identical contents, just a fresh object. 
seems reasonable to do a deep comparison here, instead of a shallow equality test.
otherwise this code resets the player mid stream for us if that playlist prop gets touched.

deep comparison for playlist

---

src/create-event-handlers/on-play.js
test/on-play.test.js

https://github.com/micnews/react-jw-player/issues/83
Solves issue with newer versions of jw player where on resume is being triggered through 'buffering' rather than 'paused'

Fix for on resume event

---

src/react-jw-player.jsx
test/react-jw-player.browser-test.js
test/react-jw-player.test.jsx

Initializing jwplayer passing DOM ref allows to use this Component inside a web component

Init jwplayer passing DOM ref instead of id

---

.gitattributes
package.json

A couple of minor compatibility improvements for developers working on Windows.
`rm -rf` isn’t available on Windows, so use `rimraf` from npm instead for cross-platform compatibility.
Add a `.gitattributes` file to force `.js` and `.jsx` files to check out with LF line endings.
By default git for Windows will check out text files with CRLF line endings, and then convert them back to LF when committing. This causes eslint to complain on Windows, because the rule `linebreak-style` is set to require LF line breaks.

Windows compatibility

---

README.md

Fix a link that was incorrectly marked up with the square brackets and parentheses transposed, so it didn't actually render as a link.

Fix markup error in README.
